export enum Environment {
  LOCAL = 'LOCAL',
  JENKINS_TEST = 'JENKINS_TEST',
  JENKINS_DEPLOYMENT = 'JENKINS_DEPLOYMENT',
  JENKINS_DEPLOYMENT_WINDOWS = 'JENKINS_DEPLOYMENT_WINDOWS',
  KUBE = 'KUBERNETES',
  PROD_KUBE = 'PROD_KUBERNETES',
  PASSIVE_CASES = 'PASSIVE_CASES',
  WEEKEND_SMOKE_TRIGGER = 'WEEKEND_SMOKE_TRIGGER',
  WEEKLY_SMOKE_TRIGGER = 'WEEKLY_SMOKE_TRIGGER',
  NON_USEINSIDER_USER_TRIGGER = 'NON_USEINSIDER_USER_TRIGGER',
  TEST_MACHINE_FROM_LOCAL = 'TEST_MACHINE_FROM_LOCAL',
}
